### PR TITLE
Create a Frequency C++ Program .

### PR DESCRIPTION
**Pull request by Pandz18**
Hello , I've created a C++ program to find the frequency of a character in a string . I would like to add more algorithms or programs that I find would be useful to students . If that is ok with you.

### CODE REVIEW

**Comment by yashasvi-goel** [comment]
please add this in the readme

**Comment by Pandz18** [comment]
> please add this in the readme

Sorry , Add what to the Readme

**Comment by Pandz18** [comment]
Oh , I understand , will do

**Comment by Pandz18** [comment]
I've deleted the file by mistake, I'll close this PR and I'll pull a new one with both changes . Apologises for the trouble @yashasvi-goel

**Pull request closed without merging**
